### ISSUE TITLE
java.io.IOException: Internal Server Error when trying to upload skin

### ISSUE THREAD

**Issue by Phoenix616** [MineLittlePony/HDSkins#30]
When I try to upload a new skin I am getting this error (both in the menu as well as ingame):

```
[20:51:29] [ForkJoinPool.commonPool-worker-8/ERROR]: Unhandled exception
java.io.IOException: Internal Server Error
	at com.minelittlepony.hdskins.util.net.MoreHttpResponses.exception(MoreHttpResponses.java:118) ~[HDSkins-6.1.2-1.15.2.jar:?]
	at com.minelittlepony.hdskins.skins.ValhallaSkinServer.upload(ValhallaSkinServer.java:138) ~[HDSkins-6.1.2-1.15.2.jar:?]
	at com.minelittlepony.hdskins.skins.ValhallaSkinServer.uploadFile(ValhallaSkinServer.java:113) ~[HDSkins-6.1.2-1.15.2.jar:?]
	at com.minelittlepony.hdskins.skins.ValhallaSkinServer.uploadPlayerSkin(ValhallaSkinServer.java:87) ~[HDSkins-6.1.2-1.15.2.jar:?]
	at com.minelittlepony.hdskins.skins.ValhallaSkinServer.performSkinUpload(ValhallaSkinServer.java:68) ~[HDSkins-6.1.2-1.15.2.jar:?]
	at com.minelittlepony.hdskins.client.SkinUploader.lambda$uploadSkin$0(SkinUploader.java:209) ~[HDSkins-6.1.2-1.15.2.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_241]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_241]
```

**Mod version:** v6.1.2-1.15.2

**Fabric loader:** 0.7.8+build.184-1.15.2

**Comment by Sollace** [comment]
This is coming from the skin server @killjoy1221

**Comment by Sollace** [comment]
Please also post the skin you're trying to upload.

**Comment by Phoenix616** [comment]
Here is the skin: ![MineLP Twilight Sparkle_swag2_human_new_multi](https://user-images.githubusercontent.com/5768781/79270938-e9260a80-7e96-11ea-97d4-e679a29e5fd1.png)

**Comment by killjoy1221** [comment]
This is what the server reports when I try to upload your skin.

> `PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f8ecaf52b30>`

This is usually a bad png image. Try fiddling with the settings when exporting it.

**Comment by Phoenix616** [comment]
Uh, now it worked. Re-saved it from the xcf and not a modified png in GIMP this time. Didn't even use any special settings. 

Here is the new, working, skin file maybe it's of any interest: 
![MineLP Twilight Sparkle_swag2_human_new_multi](https://user-images.githubusercontent.com/5768781/79272378-44f19300-7e99-11ea-8f2f-191b88e1d08e.png)
