### ISSUE TITLE
Chunks sometimes fail to render on server

### ISSUE THREAD

**Issue by Phoenix616** [MineLittlePony/HDSkins#31]
![2020-05-14_00 52 57](https://user-images.githubusercontent.com/5768781/81877707-b5193480-957d-11ea-8b69-12d9e3c1db7b.png)

Seems to only happen on a multiplayer server after world/server switch as far as I can tell. Server that I noticed it on is using Paper b282 and Waterfall b344. Removing HDSkins removes the issue. 

Errors in client log:

```
[00:52:48] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
        at net.minecraft.class_269.method_1172(class_269.java:220) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_634.method_11099(class_634.java:2106) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
[00:52:48] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
        at net.minecraft.class_269.method_1172(class_269.java:220) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_634.method_11099(class_634.java:2106) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
[00:52:48] [main/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
        at net.minecraft.class_269.method_1172(class_269.java:220) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_634.method_11099(class_634.java:2106) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_2755.method_11860(class_2755.java:122) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_2755.method_11054(class_2755.java:16) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_310.method_1523(class_310.java:956) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.class_310.method_1514(class_310.java:619) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at net.minecraft.client.main.Main.main(Main.java:204) [intermediary-1.15.2-MB_Modpack_pre1.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.8.2+build.194.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.8.2+build.194.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.8.2+build.194.jar:?]
```

**Comment by Phoenix616** [comment]
Well it only happens with this mod installed and no other one so I'm pretty sure it has something to do with it...

**Comment by Sollace** [comment]
No. Definitely not. Those stack traces are from scoreboards. HDSkins only changes the skin you see on the front end. It doesn't touch any data or communications with the server

**Comment by Phoenix616** [comment]
That's really strange then that it would only appear with the mod installed. 🤔 Gonna look into this some more and see if I can trigger it without it.
