### ISSUE TITLE
Incompatibility with Better Beds

### ISSUE THREAD

**Issue by RowanSkie** [MineLittlePony/HDSkins#44]
Basically, when checking for what the skin looks like via certain gestures (standing, sleeping, riptide, etc), the game CTD's with this installed.

https://www.curseforge.com/minecraft/mc-mods/better-beds

It seems like HD Skins (or Kirin UI) doesn't like how Better Beds change the type of rendering it uses and lets out a null error.

Crash log:
```
---- Minecraft Crash Report ----
// Don't do that.

Time: 07/07/2021, 2:58 pm
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_827.method_3569(net.minecraft.class_2586, float, net.minecraft.class_4587, net.minecraft.class_4597, int, int)" because the return value of "net.minecraft.class_824.method_3550(net.minecraft.class_2586)" is null
	at com.minelittlepony.hdskins.client.dummy.DummyPlayerRenderer$BedHead.render(DummyPlayerRenderer.java:68)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderPlayerEntity(PlayerPreview.java:207)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderPlayerModel(PlayerPreview.java:190)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.lambda$renderWorldAndPlayer$3(PlayerPreview.java:140)
	at com.minelittlepony.common.util.render.ClippingSpace.renderClipped(ClippingSpace.java:28)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderWorldAndPlayer(PlayerPreview.java:135)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.lambda$render$2(PlayerPreview.java:120)
	at com.minelittlepony.hdskins.client.dummy.DummyPlayerRenderer.wrap(DummyPlayerRenderer.java:45)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.render(PlayerPreview.java:110)
	at com.minelittlepony.hdskins.client.gui.GuiSkins.method_25394(GuiSkins.java:394)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1114)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minelittlepony.hdskins.client.dummy.DummyPlayerRenderer$BedHead.render(DummyPlayerRenderer.java:68)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderPlayerEntity(PlayerPreview.java:207)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderPlayerModel(PlayerPreview.java:190)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.lambda$renderWorldAndPlayer$3(PlayerPreview.java:140)
	at com.minelittlepony.common.util.render.ClippingSpace.renderClipped(ClippingSpace.java:28)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.renderWorldAndPlayer(PlayerPreview.java:135)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.lambda$render$2(PlayerPreview.java:120)
	at com.minelittlepony.hdskins.client.dummy.DummyPlayerRenderer.wrap(DummyPlayerRenderer.java:45)
	at com.minelittlepony.hdskins.client.dummy.PlayerPreview.render(PlayerPreview.java:110)
	at com.minelittlepony.hdskins.client.gui.GuiSkins.method_25394(GuiSkins.java:394)

-- Screen render details --
Details:
	Screen name: com.minelittlepony.hdskins.client.gui.GuiSkins
	Mouse location: Scaled: (408, 109). Absolute: (816.000000, 219.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, betterbeds/fancybeds
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:749)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 3650048312 bytes (3480 MiB) / 6647971840 bytes (6340 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b06
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28604.99
	Virtual memory used (MB): 18812.88
	Swap memory total (MB): 12288.00
	Swap memory used (MB): 838.87
	JVM Flags: 5 total; -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms640m -Xmx8192m
	Fabric Mods: 
		betterbeds: Better Beds 1.2.0
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c3d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		hdskins: HD Skins 6.4.10
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.9.1
		minecraft: Minecraft 1.17
		org_apache_httpcomponents_httpmime: httpmime 4.3.2
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, betterbeds/fancybeds
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
```

Latest.log: https://paste.ee/p/uijCD

**Comment by Sollace** [comment]
Better Beds removed the BER for beds. >.>

~Why would anyone think that was a good idea!?~

Thanks for the report. I'll see what I can do
