### ISSUE TITLE
[bug] when having bobby and HDSkins installed, HDSkins skin chooser won't work

### ISSUE THREAD

**Issue by MimzyFang** [MineLittlePony/HDSkins#51]
Logs don't have any helpful information as far as I've seen

How to reproduce
1. Install both HDSkins and bobby and it's required dependencies
2. Start the game 
3. open the Skin Selector on the bottom right of the screen
4. it never finishes loading and looks like this 
![image](https://user-images.githubusercontent.com/43648117/173378712-0c860993-5528-466c-b641-835e6aa2a46f.png)

expected behavior 
It should load like this
![image](https://user-images.githubusercontent.com/43648117/173379430-a632aad8-3277-4b56-b28e-20492af582eb.png)

**Comment by MimzyFang** [comment]
Sister issue https://github.com/Johni0702/bobby/issues/100

**Comment by Sollace** [comment]
Found the error with bobby.

```
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: java.lang.IllegalStateException: Must be called from main thread.
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at de.johni0702.minecraft.bobby.FakeChunkStorage.getFor(FakeChunkStorage.java:93)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at de.johni0702.minecraft.bobby.FakeChunkManager.<init>(FakeChunkManager.java:89)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.world.ClientChunkManager.handler$zci000$bobbyInit(ClientChunkManager.java:553)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.world.ClientChunkManager.<init>(ClientChunkManager.java:53)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.world.ClientWorld.<init>(ClientWorld.java:172)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at com.minelittlepony.hdskins.client.dummy.DummyWorld.<init>(DummyWorld.java:78)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at com.minelittlepony.hdskins.client.dummy.DummyWorld.lambda$1(DummyWorld.java:30)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[00:32:56] [ForkJoinPool.commonPool-worker-1/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
