### ISSUE TITLE
Crash when Equipment sets contain invalid enum keys

### ISSUE THREAD

**Issue by Sollace** [MineLittlePony/HDSkins#7]
```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2019/07/17 9:04 AM
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at java.util.EnumMap.typeCheck(Unknown Source)
	at java.util.EnumMap.put(Unknown Source)
	at java.util.EnumMap.put(Unknown Source)
	at com.minelittlepony.hdskins.dummy.DummyPlayer.setEquippedStack(DummyPlayer.java:168)
	at com.google.common.collect.Maps$TransformedEntriesMap.lambda$forEach$0(Maps.java:2165)
	at java.util.LinkedHashMap.forEach(Unknown Source)
	at com.google.common.collect.Maps$TransformedEntriesMap.forEach(Maps.java:2165)
	at com.minelittlepony.hdskins.dummy.EquipmentList$EquipmentSet.apply(EquipmentList.java:104)
	at com.minelittlepony.hdskins.dummy.PlayerPreview.setEquipment(PlayerPreview.java:209)
	at com.minelittlepony.hdskins.SkinUploader.cycleEquipment(SkinUploader.java:129)
	at com.minelittlepony.hdskins.gui.GuiSkins.lambda$16(GuiSkins.java:208)
	at com.minelittlepony.common.client.gui.element.Button.onClick(Button.java:133)
	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget.java:145)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:42)
	at com.minelittlepony.hdskins.gui.GuiSkins.mouseClicked(GuiSkins.java:278)
	at net.minecraft.client.Mouse.method_1611(Mouse.java:80)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:430)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:80)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at net.minecraft.client.util.Window.pollEvents(Window.java:451)
	at net.minecraft.client.util.Window.setFullscreen(Window.java:312)
	at net.minecraft.client.MinecraftClient.updateDisplay(MinecraftClient.java:952)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:916)
	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:386)
	at net.minecraft.client.main.Main.main(Main.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.EnumMap.typeCheck(Unknown Source)
	at java.util.EnumMap.put(Unknown Source)
	at java.util.EnumMap.put(Unknown Source)
	at com.minelittlepony.hdskins.dummy.DummyPlayer.setEquippedStack(DummyPlayer.java:168)
	at com.google.common.collect.Maps$TransformedEntriesMap.lambda$forEach$0(Maps.java:2165)
	at java.util.LinkedHashMap.forEach(Unknown Source)
	at com.google.common.collect.Maps$TransformedEntriesMap.forEach(Maps.java:2165)
	at com.minelittlepony.hdskins.dummy.EquipmentList$EquipmentSet.apply(EquipmentList.java:104)
	at com.minelittlepony.hdskins.dummy.PlayerPreview.setEquipment(PlayerPreview.java:209)
	at com.minelittlepony.hdskins.SkinUploader.cycleEquipment(SkinUploader.java:129)
	at com.minelittlepony.hdskins.gui.GuiSkins.lambda$16(GuiSkins.java:208)
	at com.minelittlepony.common.client.gui.element.Button.onClick(Button.java:133)
	at net.minecraft.client.gui.widget.AbstractButtonWidget.mouseClicked(AbstractButtonWidget.java:145)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement.java:42)
	at com.minelittlepony.hdskins.gui.GuiSkins.mouseClicked(GuiSkins.java:278)
	at net.minecraft.client.Mouse.method_1611(Mouse.java:80)

-- Affected screen --
Details:
	Screen name: com.minelittlepony.hdskins.gui.GuiSkins
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:430)
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:80)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at net.minecraft.client.util.Window.pollEvents(Window.java:451)
	at net.minecraft.client.util.Window.setFullscreen(Window.java:312)
	at net.minecraft.client.MinecraftClient.updateDisplay(MinecraftClient.java:952)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:916)
	at net.minecraft.client.MinecraftClient.start(MinecraftClient.java:386)
	at net.minecraft.client.main.Main.main(Main.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_152, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 544013080 bytes (518 MB) / 973602816 bytes (928 MB) up to 1886912512 bytes (1799 MB)
	JVM Flags: 0 total; 
	Launched Version: Fabric
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 520 GL version 4.5.0 - Build 25.20.100.6472, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\dev\gradle 1.9\HDSkins\run\.\crash-reports\crash-2019-07-17_09.04.01-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
```

Diamond.json
```
{
  "item": "minecraft:diamond_helmet",
  "equipment": {
    "HEAD": "minecraft:diamond_helmet",
    "chest": "minecraft:diamond_chestplate",
    "legs": "minecraft:diamond_leggings",
    "feet": "minecraft:diamond_boots"
  }
}
```

**Comment by killjoy1221** [comment]
The solution would be to fix your json. But the better solution would be to check for null before calling setEquipmentStack

**Comment by Sollace** [comment]
The current solution is fine. It will parse case correctly, and any keys that are not a valid enum constant will resuly in the equipment set failing to parse.

**Comment by killjoy1221** [comment]
The issue is titled `Crash when Equipment sets contain invalid enum keys`. Is that resolved?
